### ISSUE TITLE
Consider using composer create-project to create Wiring application

### ISSUE THREAD

**Issue by peter279k** [ar2labs/wiring-start#10]
As title, I think we can consider releasing `wiring-start` version and use the `composer create-project ar2labs/wiring-start` to replace the `git clone https://github.com/ar2labs/wiring-start.git`.

And it's easy to versioning the `wiring-start` installer :).

@arcostasi, what do you think about this?

**Comment by arcostasi** [comment]
Excellent idea @peter279k, didn’t know about this feature, we can do it that way, for sure it will get better!

**Comment by arcostasi** [comment]
Done! follow [commit](https://github.com/ar2labs/wiring/commit/2610a5c47ca1f22e3be6b6c279a1d5e2da55391a)
