### ISSUE TITLE
zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by peter279k** [ar2labs/wiring-start#9]
As title, it seems that the `zendframework/zend-diactoros` package has been [abandoned](https://github.com/zendframework/zend-diactoros).

And the package suggests using `laminas/laminas-diactoros` package instead.

@arcostasi, do we plan to move to maintained `laminas/laminas-diactoros` package?

**Comment by arcostasi** [comment]
yes @peter279k, let's change, I already tested it with the wiring core and it worked normally!

**Comment by arcostasi** [comment]
Fixed in this [update](https://github.com/ar2labs/wiring-start/commit/b5784e84907c9b2593e5e54a5b215269739c761a) and updated other packages!

**Comment by alissonl3** [comment]
Good luck 👏👏

Em qui, 23 de jul de 2020 11:37, Anderson Costa <notifications@github.com>
escreveu:
